### ISSUE TITLE
使用build命令打包后，打包文件放到web服务器中页面不显示

### ISSUE THREAD

**Issue by moccen** [iview/iview-cli#10]
使用iview-cli工具新建项目，新建完成后执行npm install和npm run dev命令，浏览器调试页面正常显示，接下来使用npm run build命令打包，将生成的index_prod.html和dist文件夹一起放入tomcat和nodejs中都无法正常显示页面

**Comment by 634750802** [comment]
同样的问题，怎么解决的？

**Comment by zhangweia** [comment]
@moccen 我也遇到同样的问题，请问怎么解决的啊，新手小白求教
