### ISSUE TITLE
iView-cli-mac.dmg 2.0版本什么时候能支持？

### ISSUE THREAD

**Issue by denghp** [iview/iview-cli#12]

**Comment by icarusion** [comment]
已有

**Comment by denghp** [comment]
release 2.0下载的只有源码,没看到编译好的.dmg版本，  还是说在别的地方有下载地址？

**Comment by icarusion** [comment]
https://www.iviewui.com/cli

**Comment by denghp** [comment]
点击下载跳转就没有然后了，不知道是什么原因？
操作系统 macOS 10.12.3
浏览器 chrome 58.0.3029.110 (64-bit)
