### ISSUE TITLE
English version

### ISSUE THREAD

**Issue by michalskop** [iview/iview-cli#15]
Is it possible to switch to English (or other languages)? I can see different locales, but when I start iView (linux 64 version), it is in Chinese with no obvious option to switch to English.

**Comment by icarusion** [comment]
We will add English in next version.

**Comment by MrSunshyne** [comment]
This looks awesome. Do you have a schedule for the next version ?

**Comment by ghost** [comment]
Any update on this? Would be awesome to know what I'm pressing :) Happy to contribute somehow if you can tell me how.

**Comment by icarusion** [comment]
We now recommend using Vue CLI 3 to manage your project now, and we've given up on maintaining the iView CLI.
