### ISSUE TITLE
创建的项目在mac下编译失败

### ISSUE THREAD

**Issue by juzhiyuan** [iview/iview-cli#31]
发现issue里有同样的问题，[地址](https://github.com/iview/iview-admin/issues/82)，希望可以更新到iview-cli中

**Comment by qianshanding** [comment]
我也碰到这个问题，请问怎么解决
ERROR in ./src/main.js
Module not found: Error: Can't resolve 'iview-loader' in '/Users/xxx/front'
 @ ./src/main.js 7:0-28
 @ multi (webpack)-dev-server/client?http://localhost:8081 webpack/hot/dev-server ./src/main

ERROR in ./src/router.js
Module not found: Error: Can't resolve 'iview-loader' in '/Users/xxx/front'
 @ ./src/router.js 7:15-54
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8081 webpack/hot/dev-server ./src/main

**Comment by juzhiyuan** [comment]
![image](https://user-images.githubusercontent.com/2106987/33584477-8e9b2dfa-d99a-11e7-868a-03e9ce5d9ee1.png)

**Comment by iocool** [comment]
看了一下错误,显示缺少iview-loader,然后在package.json里没有发现这个依赖,运行一下

npm i iview-loader --save-dev

然后再npm run dev 就可以了

具体什么原因编译失败,不是很清楚,但是这样可以解决这个问题
